### ISSUE TITLE
Readme adjustments

### ISSUE THREAD

**Issue by Kenny606** [theOtherLuke/nordlynx-router#1]
Everything worked great!! Thank you very much for this!!!
I was sick of the bandwith I was getting on OpenVPN. I just jumped from 100Mbps to 650-700 Mbps thanks to this :-)
I almost bought that damn PrivacyHero unit which I didn't want to get my bandwith back but this worked perfectly with my Protectli

Just FYI though a few really quick suggestions on the documentation for idiots like me lol:

In the router Readme, this may caused by a change to the NordVPN Client since you wrote this.
   I had to whitelist port 67/68 to in order for dnsmasq to handout IP's.
   I probably only needed 67 (server port) and not the client port 68 but I added both.
   Otherwise DNSMasq showed it was getting the requests but failing to send the offers while Nord was connected.

The monitor script:
   In case you have an idiot like me that takes 20 minutes to think of why the service wasn't working haha :)
   You might want to add chmod +x /root/check-connectivity.sh
   I have no idea why I didn't do it in the first place but I didn't lol

Thanks again for this!

**Comment by theOtherLuke** [comment]
Thanks for the input. I will update to account for making check-connectivity.sh executable and the possibly needing to whitelist ports 67 and maybe 68
